/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : string, 'name' : string }
export interface ChecklistConfig {
  'categories' : Array<Category>,
  'items' : Array<ChecklistItem>,
}
export interface ChecklistItem {
  'id' : string,
  'categoryId' : string,
  'defaultChecked' : boolean,
  'name' : string,
  'prompt' : string,
}
export type ExternalBlob = Uint8Array;
export interface LogEntry {
  'id' : string,
  'title' : [] | [string],
  'mileage' : [] | [bigint],
  'owner' : Principal,
  'notes' : string,
  'timestamp' : Time,
}
export interface PreTripChecklist {
  'driverId' : Principal,
  'checked' : Array<[string, boolean]>,
  'signature' : string,
  'timestamp' : Time,
  'driverName' : string,
}
export interface Question {
  'id' : string,
  'status' : QuestionStatus,
  'adminReply' : [] | [string],
  'owner' : Principal,
  'questionText' : string,
  'timestamp' : Time,
}
export type QuestionStatus = { 'open' : null } |
  { 'answered' : null };
export interface SavedChecklist {
  'driverId' : Principal,
  'checked' : Array<[string, boolean]>,
  'signature' : string,
  'timestamp' : Time,
  'items' : Array<ChecklistItem>,
  'driverName' : string,
}
export type Time = bigint;
export interface UploadReference {
  'id' : string,
  'contentType' : string,
  'owner' : Principal,
  'blob' : ExternalBlob,
  'name' : string,
  'size' : bigint,
  'timestamp' : Time,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'answerQuestion' : ActorMethod<[Principal, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCheckpointHistory' : ActorMethod<[], undefined>,
  'createLogEntry' : ActorMethod<
    [[] | [string], string, [] | [bigint]],
    string
  >,
  'deleteLogEntry' : ActorMethod<[string], undefined>,
  'getAllLogEntries' : ActorMethod<[], Array<[Principal, Array<LogEntry>]>>,
  'getAllQuestions' : ActorMethod<[], Array<[Principal, Array<Question>]>>,
  'getAllSavedChecklists' : ActorMethod<
    [],
    Array<[Principal, Array<SavedChecklist>]>
  >,
  'getAllUploads' : ActorMethod<[], Array<[Principal, Array<UploadReference>]>>,
  'getCallerLogEntries' : ActorMethod<[], Array<LogEntry>>,
  'getCallerQuestions' : ActorMethod<[], Array<Question>>,
  'getCallerUploads' : ActorMethod<[], Array<UploadReference>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChecklistConfig' : ActorMethod<[], ChecklistConfig>,
  'getCompletedChecklists' : ActorMethod<[], Array<SavedChecklist>>,
  'getUserLogEntry' : ActorMethod<[Principal, string], LogEntry>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserQuestion' : ActorMethod<[Principal, string], Question>,
  'getUserUpload' : ActorMethod<[Principal, string], UploadReference>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveChecklist' : ActorMethod<
    [string, string, Array<[string, boolean]>],
    undefined
  >,
  'saveChecklistFull' : ActorMethod<[PreTripChecklist], undefined>,
  'submitQuestion' : ActorMethod<[string], string>,
  'updateLogEntry' : ActorMethod<
    [string, [] | [string], string, [] | [bigint]],
    undefined
  >,
  'updateQuestionStatus' : ActorMethod<
    [Principal, string, QuestionStatus],
    undefined
  >,
  'updateUserProfile' : ActorMethod<[string], undefined>,
  'uploadDocument' : ActorMethod<
    [ExternalBlob, string, string, bigint],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];