/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const LogEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Opt(IDL.Text),
  'mileage' : IDL.Opt(IDL.Int),
  'owner' : IDL.Principal,
  'notes' : IDL.Text,
  'timestamp' : Time,
});
export const QuestionStatus = IDL.Variant({
  'open' : IDL.Null,
  'answered' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Text,
  'status' : QuestionStatus,
  'adminReply' : IDL.Opt(IDL.Text),
  'owner' : IDL.Principal,
  'questionText' : IDL.Text,
  'timestamp' : Time,
});
export const ChecklistItem = IDL.Record({
  'id' : IDL.Text,
  'defaultChecked' : IDL.Bool,
  'name' : IDL.Text,
  'prompt' : IDL.Text,
});
export const SavedChecklist = IDL.Record({
  'driverId' : IDL.Principal,
  'checked' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'signature' : IDL.Text,
  'timestamp' : Time,
  'items' : IDL.Vec(ChecklistItem),
  'driverName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UploadReference = IDL.Record({
  'id' : IDL.Text,
  'contentType' : IDL.Text,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChecklistSection = IDL.Record({
  'title' : IDL.Text,
  'items' : IDL.Vec(ChecklistItem),
});
export const ChecklistConfig = IDL.Record({
  'sections' : IDL.Vec(ChecklistSection),
});
export const PreTripChecklist = IDL.Record({
  'driverId' : IDL.Principal,
  'checked' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'signature' : IDL.Text,
  'timestamp' : Time,
  'driverName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'answerQuestion' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCheckpointHistory' : IDL.Func([], [], []),
  'createLogEntry' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(IDL.Int)],
      [IDL.Text],
      [],
    ),
  'deleteLogEntry' : IDL.Func([IDL.Text], [], []),
  'getAllLogEntries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(LogEntry)))],
      ['query'],
    ),
  'getAllQuestions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Question)))],
      ['query'],
    ),
  'getAllSavedChecklists' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(SavedChecklist)))],
      ['query'],
    ),
  'getAllUploads' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(UploadReference)))],
      ['query'],
    ),
  'getCallerLogEntries' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
  'getCallerQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getCallerUploads' : IDL.Func([], [IDL.Vec(UploadReference)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChecklistByDate' : IDL.Func([Time], [IDL.Opt(SavedChecklist)], ['query']),
  'getChecklistConfig' : IDL.Func([], [ChecklistConfig], ['query']),
  'getCompletedChecklists' : IDL.Func([], [IDL.Vec(SavedChecklist)], ['query']),
  'getUserLogEntry' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [LogEntry],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserQuestion' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [Question],
      ['query'],
    ),
  'getUserUpload' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [UploadReference],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveChecklist' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      [],
      [],
    ),
  'saveChecklistFull' : IDL.Func([PreTripChecklist], [], []),
  'submitQuestion' : IDL.Func([IDL.Text], [IDL.Text], []),
  'updateLogEntry' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(IDL.Int)],
      [],
      [],
    ),
  'updateQuestionStatus' : IDL.Func(
      [IDL.Principal, IDL.Text, QuestionStatus],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func([IDL.Text], [], []),
  'uploadDocument' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const LogEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Opt(IDL.Text),
    'mileage' : IDL.Opt(IDL.Int),
    'owner' : IDL.Principal,
    'notes' : IDL.Text,
    'timestamp' : Time,
  });
  const QuestionStatus = IDL.Variant({
    'open' : IDL.Null,
    'answered' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Text,
    'status' : QuestionStatus,
    'adminReply' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'questionText' : IDL.Text,
    'timestamp' : Time,
  });
  const ChecklistItem = IDL.Record({
    'id' : IDL.Text,
    'defaultChecked' : IDL.Bool,
    'name' : IDL.Text,
    'prompt' : IDL.Text,
  });
  const SavedChecklist = IDL.Record({
    'driverId' : IDL.Principal,
    'checked' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'signature' : IDL.Text,
    'timestamp' : Time,
    'items' : IDL.Vec(ChecklistItem),
    'driverName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UploadReference = IDL.Record({
    'id' : IDL.Text,
    'contentType' : IDL.Text,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChecklistSection = IDL.Record({
    'title' : IDL.Text,
    'items' : IDL.Vec(ChecklistItem),
  });
  const ChecklistConfig = IDL.Record({
    'sections' : IDL.Vec(ChecklistSection),
  });
  const PreTripChecklist = IDL.Record({
    'driverId' : IDL.Principal,
    'checked' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'signature' : IDL.Text,
    'timestamp' : Time,
    'driverName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'answerQuestion' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCheckpointHistory' : IDL.Func([], [], []),
    'createLogEntry' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(IDL.Int)],
        [IDL.Text],
        [],
      ),
    'deleteLogEntry' : IDL.Func([IDL.Text], [], []),
    'getAllLogEntries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(LogEntry)))],
        ['query'],
      ),
    'getAllQuestions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Question)))],
        ['query'],
      ),
    'getAllSavedChecklists' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(SavedChecklist)))],
        ['query'],
      ),
    'getAllUploads' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(UploadReference)))],
        ['query'],
      ),
    'getCallerLogEntries' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
    'getCallerQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getCallerUploads' : IDL.Func([], [IDL.Vec(UploadReference)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChecklistByDate' : IDL.Func(
        [Time],
        [IDL.Opt(SavedChecklist)],
        ['query'],
      ),
    'getChecklistConfig' : IDL.Func([], [ChecklistConfig], ['query']),
    'getCompletedChecklists' : IDL.Func(
        [],
        [IDL.Vec(SavedChecklist)],
        ['query'],
      ),
    'getUserLogEntry' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [LogEntry],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserQuestion' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [Question],
        ['query'],
      ),
    'getUserUpload' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [UploadReference],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveChecklist' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        [],
        [],
      ),
    'saveChecklistFull' : IDL.Func([PreTripChecklist], [], []),
    'submitQuestion' : IDL.Func([IDL.Text], [IDL.Text], []),
    'updateLogEntry' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(IDL.Int)],
        [],
        [],
      ),
    'updateQuestionStatus' : IDL.Func(
        [IDL.Principal, IDL.Text, QuestionStatus],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func([IDL.Text], [], []),
    'uploadDocument' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };